stages:
  - setup
  - triggers


variables:
  ALL_PIPELINES: "False"

generate_includes:
  stage: setup
  script:
    - chmod -x gitlab_ci/generate_includes.sh
    - sh gitlab_ci/generate_includes.sh generate_includes
  artifacts:
    paths:
      - gitlab_ci/includes.yml

all_pipelines:
  stage: triggers
  variables:
    ALL_PIPELINES: "True" 
  trigger:
    include :
      - artifact: gitlab_ci/includes.yml
        job: generate_includes
  rules:
    - changes:
      - .gitlab-ci.yml
      - gitlab_ci/*

whole_pipeline:
  stage: triggers
  trigger:
    include:
      - gitlab_ci/classic_pipeline.yml
  rules:
    - if: $ALL_PIPELINES == "True"
      when: never
    - changes:
      - src/*
      - tests/*

building_pipeline:
  stage: triggers
  trigger:
    include:
      - gitlab_ci/build_pipeline.yml
  rules:
    - if: $ALL_PIPELINES == "True"
      when: never
    - changes:
      - src/*
      - CMakeLists.txt
      - Makefile

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"     # Run for main branch
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH =~ /feature/  # Run for feature branches
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"  # Run on merge requests
